version: "2"

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wsl_v5
    - zerologlint
  exclusions:
    rules:
      - linters:
          - contextcheck
        text: "^Non-inherited new context"
      - path: (.*)_test.go
        linters:
          - fatcontext
        text: "nested context in loop"
      - linters:
          - revive
        text: "^(exported|unexported-return)"
      - linters:
          - godox
        text: "TODO"
      - path: (.+)_test.go
        linters:
          - revive
        text: "^(add-constant|context-as-argument|context-keys-type)"
      - path: (.+)_test.go
        linters:
          - staticcheck
        text: "SA1029"
      - path: examples/(.+)/main.go
        linters:
          - forbidigo
          - forcetypeassert
          - mnd
          - revive
        text: "(forbidden by pattern|type assertion|Magic number|package-comments)"
      - path: example_test.go
        linters:
          - testableexamples
        text: "missing output for example"
      - path: agent/agent.go
        linters:
          - exhaustive
          - gochecknoglobals
          - gochecknoinits
        text: "(missing cases in switch|is a global variable|don't use `init` function)"
      - path: ui/terminal.go
        linters:
          - exhaustive
          - gochecknoglobals
          - gochecknoinits
        text: "(missing cases in switch|is a global variable|don't use `init` function)"
      - linters:
          - cyclop
        path: (agent/agent.go|tool/grep.go|tool/ls.go|tool/ls_test.go)
        text: "cyclomatic complexity"
      - linters:
          - err113
        path: tool/(grep|ls).go
        text: "dynamic errors"
      - linters:
          - funlen
        path: tool/ls_test.go
        text: "Function.*is too long"
      - linters:
          - mnd
        path: (conversation|agent/config|config).go
        text: "Magic number"
      - linters:
          - gochecknoglobals
        path: tool/(ls|tool).go
        text: "global variable"
      - linters:
          - gosec
        path: tool/(grep|ls)
        text: "(G204|G703|G301|G306)"
      - linters:
          - testpackage
        path: (.+)_test.go
        text: "package should be"
      - linters:
          - intrange
        path: conversation/conversation_test.go
        text: "for loop"
      - linters:
          - lll
        path: tool/grep.go
        text: "line is"
      - linters:
          - forbidigo
        path: main.go
        text: "fmt.Println"
      - linters:
          - nlreturn
        path: config.go
        text: "return"
      - linters:
          - ineffassign
        path: tool/grep.go
        text: "ineffectual assignment"

linters-settings:
  wsl_v5:
    allow-first-in-block: true
    allow-whole-block: false
    branch-max-lines: 2